set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=                                                                                    A
set A=
set "MYISO=\_ISO\WINDOWS\WIN10\_000_Windows 10 x86 Feb 2019.iso"
set MYISO=DONE
